### ISSUE TITLE
another name for PixelMod

### ISSUE THREAD

**Issue by zhaonian** [zhaonian/LogoSwap#8]
please post some potential names here :)

**Comment by DaviesX** [comment]
Logo swap through pixel mod. Good name.

**Comment by zhaonian** [comment]
How about `EyesPixel`, then we can change the library's package id to `org.eyes.eyespixel` just like what I have for the app `io.zluan.logoswap`?

**Comment by DaviesX** [comment]
Still prefer pixelmod.
